apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zao5zjxxy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zao5zjxxy-python 
  name: zao5zjxxy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zao5zjxxy-python 
